name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements-testing.txt
      - name: Run tests
        run: pytest
